use_frameworks!

platform :ios, '8.0'

target 'FPSLabel_Example' do
  pod 'FPSLabel', :path => '../'

  target 'FPSLabel_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
